export const TUNING = {
  lives: 3,
  maxLevel: 15,
  columns: 6,
  visibleCapacity: 36,
  spacingX: 2.5,
  spacingY: 2,
  formationTop: 11,
  stepX: 0.65,
  stepY: 0.6,
  playerSpeed: 9,
  tapInterval: 0.2,
  holdInterval: 0.24,
  hitPause: 5,
  protection: 3,
  levelTransition: 1.5,
  launchTelegraph: 0.7,
  killPoints: 100,
  cancelPoints: 50,
} as const;
