import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('screenshots',{recursive:true});
const browser = await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await page.waitForSelector('canvas'); await page.waitForTimeout(2000);
await page.screenshot({path:'screenshots/start-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Launch mission'}).click();
await page.keyboard.down('Space');await page.keyboard.down('ArrowRight');await page.waitForTimeout(1100);await page.keyboard.up('ArrowRight');await page.keyboard.down('ArrowLeft');await page.waitForTimeout(1600);await page.keyboard.up('ArrowLeft');await page.keyboard.up('Space');
await page.keyboard.press('Escape'); await page.getByRole('heading',{name:'MISSION PAUSED'}).waitFor();
await page.screenshot({path:'screenshots/paused-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Resume mission'}).click();await page.waitForTimeout(500);
await page.screenshot({path:'screenshots/gameplay-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);
await page.screenshot({path:'screenshots/mobile-layout.png',fullPage:true});
const info=await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,text:document.body.innerText}));
await writeFile('screenshots/browser-smoke.json',JSON.stringify({errors,info},null,2));
console.log(JSON.stringify({errors,horizontalOverflow:info.documentWidth>info.width,text:info.text.slice(0,1000)},null,2));
await browser.close();if(errors.length||info.documentWidth>info.width)process.exitCode=1;
